language: go
sudo: false
before_install:
  - make get-tools
install: true
script:
  - make test
  - make basic-lint
go:
  - 1.7
  - 1.8
  - master
notifications:
  email:
    - talek-dev@googlegroups.com
